# Basic Site Settings
locale                   : "en-US"
site_theme               : "default"
title                    : "Mustafa Guzel Lab"
title_separator          : "-"
name                     : &name "Mustafa Guzel"
description              : &description "Food Microbiology, Antimicrobial Resistance, and Phage Biology Lab"
url                      : https://musguzel.github.io
baseurl                  : ""
repository               : "musguzel/musguzel.github.io"

# Site Author (Sidebar Info)
author:
  avatar           : "profile.png"
  name             : "Mustafa Guzel"
  pronouns         :  
  bio              : "Food microbiologist studying antimicrobial resistance, phage biology, microbial genomics, and food safety."
  location         : "Turkey"
  employer         : "Your University or Institute"
  uri              :  
  email            : "your.email@example.com" 

  googlescholar    : "https://scholar.google.com"
  orcid            : "http://orcid.org/your-orcid-id"
  pubmed           : "https://pubmed.ncbi.nlm.nih.gov/"
  researchgate     : "https://www.researchgate.net/"
  github           : "musguzel"
  linkedin         : "your-linkedin-id"

# Publication Categories
publication_category:
  books:
    title: 'Books'
  manuscripts:
    title: 'Journal Articles'    
  conferences:
    title: 'Conference Papers'

# Site Settings
breadcrumbs              : false
words_per_minute         : 160
future                   : true
read_more                : "disabled"
talkmap_link             : false
comments:
  provider               : false

atom_feed:
  hide                   : false

# Analytics (you can enable later if desired)
analytics:
  provider               :  false

# Reading Files
include:
  - .htaccess
  - _pages
  - files

exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .github
  - .jekyll-assets-cache
  - .sass-cache
  - node_modules
  - Gemfile
  - LICENSE
  - README
  - tmp
  - vendor

keep_files:
  - .git

encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Conversion
markdown: kramdown
highlighter: rouge

# Collections (pages to include)
collections:
  teaching:
    output: true
    permalink: /:collection/:path/
  publications:
    output: true
    permalink: /:collection/:path/
  portfolio:
    output: true
    permalink: /:collection/:path/
  talks:
    output: true
    permalink: /:collection/:path/

# Default settings for collections
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: false
      related: true
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
  - scope:
      path: ""
      type: teaching
    values:
      layout: single
      author_profile: true
  - scope:
      path: ""
      type: publications
    values:
      layout: single
      author_profile: true
  - scope:
      path: ""
      type: portfolio
    values:
      layout: single
      author_profile: true
  - scope:
      path: ""
      type: talks
    values:
      layout: talk
      author_profile: true

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed

# Plugins (leave as-is for now)
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from
  - jemoji

timezone: Etc/UTC
